#!/bin/sh
set -e -x

#
# Initialization
#

# Check if root
if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

# Read profile parameter
if [ "" = "$1" ] ; then 
  echo "You need to specify a profile" 1>&2
fi
if [ -d "$1" ] ; then
  PROFILE="$1"
else
  echo "Profile $PROFILE not found" 1>&2
  exit 1
fi

# Read rootfs path
if [ "" = "$2" ] ; then 
  echo "You need to specify a path to the target rootfs" 1>&2
  exit 1
else
  if [ -e "$2" ] ; then
    ROOTFS=`readlink -m $2`
  else 
    echo "Root dir $2 not found" 1>&2
    exit 1
  fi
fi
ROOTFS=`cd $ROOTFS; pwd`

# Read settings
if [ -e $PROFILE/main.conf ] ; then
  . $PROFILE/main.conf
else
  echo "Profile lacks main settings" 1>&2
  exit 1
fi


#
# Main
#

# Add QEMU static binary
# TODO: compare $ARCH to current arch, and select proper one
cp /usr/bin/qemu-arm-static $ROOTFS/usr/bin

# Clean apt
chroot $ROOTFS apt-get autoremove
chroot $ROOTFS apt-get clean
rm -rf $ROOTFS/var/cache/apt/*
rm -rf $ROOTFS/var/lib/apt/lists/*

# Clean logs
rm -rf $ROOTFS/var/log/*

# History
rm -rf $ROOTFS/root/.bash_history
