#!/bin/sh
set -e -x

#
# Initialization
#

# Check if root
if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

# Read profile parameter
if [ "" = "$1" ] ; then 
  echo "You need to specify a profile" 1>&2
fi
if [ -d "$1" ] ; then
  PROFILE="$1"
else
  echo "Profile $PROFILE not found" 1>&2
  exit 1
fi

# Read rootfs path
if [ "" = "$2" ] ; then 
  echo "You need to specify a path to the target rootfs" 1>&2
  exit 1
else
  if [ -e "$2" ] ; then
    ROOTFS=`readlink -m $2`
  else 
    echo "Root dir $2 not found" 1>&2
    exit 1
  fi
fi

# Read settings
if [ -e $PROFILE/main.conf ] ; then
  . $PROFILE/main.conf
else
  echo "Profile lacks main settings" 1>&2
  exit 1
fi


#
# Main
#

# Mount
if [ ! -e "/media/Boot" ] ; then
  mkdir /media/Boot
  mount /dev/mmcblk0p1 /media/Boot
fi
if [ ! -e "/media/Root" ] ; then
  mkdir /media/Root
  mount /dev/mmcblk0p2 /media/Root
fi

# Sync files
cd $ROOTFS
rsync --archive --sparse --progress --delete --delete-excluded --exclude '/boot/*' --exclude /usr/bin/qemu-arm-static . /media/Root/
cd boot
rsync --archive --sparse --progress --delete . /media/Boot/

# lost+found directories
test -d "/media/Boot/lost+found" || mkdir --mode=0700 "/media/Boot/lost+found"
test -d "/media/Root/lost+found" || mkdir --mode=0700 "/media/Root/lost+found"

# Unmount
sync
umount /media/Root
[ -e "/media/Root" ] && rmdir /media/Root
umount /media/Boot
[ -e "/media/Boot" ] && rmdir /media/Boot
